# Generated by Django 5.1.5 on 2025-01-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_customuser_is_verified_customuser_verification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification_token',
        ),
    ]
