version: '3.8'

services:
  app:
    build:
      context: .
    container_name: reqcluster_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
      - MONGO_URI=mongodb://mongodb:27017
    networks:
      - app-network

  mongodb:
    image: mongo:6
    container_name: reqcluster_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongo_data:
