# Generated by Django 5.1.5 on 2025-02-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='requisitos_digitados',
            field=models.TextField(blank=True),
        ),
    ]
