# Generated by Django 5.1.5 on 2025-03-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_auto_20250221_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
