# Generated by Django 3.1.12 on 2025-03-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20250221_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('admin', 'Administrador'), ('normal', 'Usuário Normal')], default='normal', max_length=10),
        ),
    ]
