# Generated by Django 5.1.5 on 2025-02-19 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisito', models.CharField(max_length=255)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='requisitos/')),
                ('tipo', models.CharField(blank=True, choices=[('funcional', 'Funcional'), ('nao_funcional', 'Não Funcional')], max_length=20, null=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='projetos.projeto')),
            ],
        ),
    ]
