# Generated by Django 3.1.12 on 2025-02-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto_id', models.IntegerField(default=0)),
                ('requisito', models.CharField(max_length=255)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='requisitos/')),
                ('tipo', models.CharField(blank=True, choices=[('funcional', 'Funcional'), ('nao_funcional', 'Não Funcional')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'requisitos',
            },
        ),
    ]
