# Generated by Django 3.1.12 on 2025-03-02 21:48

from django.db import migrations, models
import djongo.models.fields
import requisitos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto_id', models.IntegerField(unique=True)),
                ('requisitos', djongo.models.fields.JSONField()),
                ('funcionais', djongo.models.fields.JSONField()),
                ('nao_funcionais', djongo.models.fields.JSONField()),
                ('grupos', djongo.models.fields.JSONField()),
                ('caracteristica_grupo', djongo.models.fields.JSONField()),
                ('status', djongo.models.fields.JSONField(default=requisitos.models.status_default)),
            ],
            options={
                'db_table': 'requisitos',
            },
        ),
    ]
