# Generated by Django 3.1.12 on 2025-03-18 01:40

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('requisitos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisito',
            name='funcionais',
            field=djongo.models.fields.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='nao_funcionais',
            field=djongo.models.fields.JSONField(default=list),
        ),
    ]
