# Generated by Django 3.1.12 on 2025-03-19 02:03

import bson.objectid
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('requisitos', '0002_auto_20250317_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisito',
            name='id',
        ),
        migrations.AddField(
            model_name='requisito',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False),
        ),
    ]
